version: "3.8"

services:
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    env_file:
      - .env/.env.postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.8
    env_file:
      - .env/.env.pgadmin
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env/.env.backend
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - imgs:/var/backend/static/img

  frontend:
    image: ghcr.io/frontend-park-mail-ru/2023_2_rabotyagi:dev
    environment:
      - API_URL=http://localhost
      - MOCK=false
      - NODE_ENV=development
    ports:
      - 3000:3000
    entrypoint: npm run dev-linux

volumes:
  postgres:
  pgadmin:
  imgs:
