version: "3.8"
services:
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=youla
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    image: backend_now
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - ALLOW_ORIGIN=localhost
      - PORT_BACKEND=8080
      - POSTGRES_DB=youla # для обратной совместимости пока оставил
      - POSTGRES_USER=postgres # для обратной совместимости пока оставил
      - POSTGRES_PASSWORD=password # для обратной совместимости пока оставил
      - URL_DATA_BASE=postgres://postgres:password@postgres:5432/youla?sslmode=disable
      - SCHEMA=http://
    depends_on:
      - postgres
    volumes:
      - ./db/img:/var/backend/db/img

volumes:
  postgres:
