global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "backend"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ 'backend:8080' ]
