global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "backend"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ 'backend:8080' ]

  - job_name: "backend_fs"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ 'backend-fs:8081' ]

  - job_name: "backend_auth"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ 'backend-auth:8082' ]
