{
 "title": "Goods-galaxy",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "backend, backend_fs, backend_auth"
   }
  ]
 },
 "panels": [
  { "title": "Service backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "rate http",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(backend_http_request_statuses_total{path!=\"/api/v1/metrics\" , method!=\"OPTIONS\"}[1m])) by (path, method)",
     "legendFormat": "{{path}}_{{method}}"
    }
   ]
  },
  {
   "title": "rate http status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(backend_http_request_statuses_total{path!=\"/api/v1/metrics\", method!=\"OPTIONS\"}[1m])",
     "legendFormat": "{{path}}_{{method}}_{{status}}"
    }
   ]
  },
  {
   "title": "http durartion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backend_http_duration{path!=\"/api/v1/metrics\" , method!=\"OPTIONS\"}",
     "legendFormat": "{{path}}_{{method}}_{{status}}_{{quantile}}"
    }
   ]
  },
  { "title": "Service backend-fs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "rate http",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(backend_fs_http_request_statuses_total{path!=\"/api/v1/metrics\", method!=\"OPTIONS\"}[1m])) by (path, method)",
     "legendFormat": "{{path}}_{{method}}"
    }
   ]
  },
  {
   "title": "rate http status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(backend_fs_http_request_statuses_total{path!=\"/api/v1/metrics\", method!=\"OPTIONS\"}[1m])",
     "legendFormat": "{{path}}_{{method}}_{{status}}"
    }
   ]
  },
  {
   "title": "http durartion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backend_fs_http_duration{path!=\"/api/v1/metrics\" , method!=\"OPTIONS\"}",
     "legendFormat": "{{path}}_{{method}}_{{status}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "grpc duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backend_fs_grpc_duration",
     "legendFormat": "{{method}}_quantile_{{quantile}}"
    }
   ]
  },
  {
   "title": "rate grpc total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(backend_fs_grpc_call_total{}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "rate grpc errors total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(backend_fs_grpc_call_error_total{}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Service backend-auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "rate grpc total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(backend_auth_grpc_call_total{}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "rate grpc errors total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(backend_auth_grpc_call_error_total{}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "grpc duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backend_auth_grpc_duration",
     "legendFormat": "{{method}}_quantile_{{quantile}}"
    }
   ]
  }
 ]
}