// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package delivery

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (CommentListResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*CommentListResponse) UnmarshalJSON([]byte) error        { return nil }
func (CommentListResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*CommentListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CommentListResponse *CommentListResponse

func (OrderListResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OrderListResponse) UnmarshalJSON([]byte) error        { return nil }
func (OrderListResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OrderListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OrderListResponse *OrderListResponse

func (OrderResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OrderResponse) UnmarshalJSON([]byte) error        { return nil }
func (OrderResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OrderResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OrderResponse *OrderResponse

func (ProductInSearchListResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ProductInSearchListResponse) UnmarshalJSON([]byte) error        { return nil }
func (ProductInSearchListResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ProductInSearchListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProductInSearchListResponse *ProductInSearchListResponse

func (ProductListResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ProductListResponse) UnmarshalJSON([]byte) error        { return nil }
func (ProductListResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ProductListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProductListResponse *ProductListResponse

func (ProductResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ProductResponse) UnmarshalJSON([]byte) error        { return nil }
func (ProductResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ProductResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProductResponse *ProductResponse

func (ResponseAPIYoomany) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ResponseAPIYoomany) UnmarshalJSON([]byte) error        { return nil }
func (ResponseAPIYoomany) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ResponseAPIYoomany) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ResponsePaymentAPI *ResponseAPIYoomany
