basePath: /api/v1
definitions:
  delivery.ErrorResponse:
    properties:
      body:
        $ref: '#/definitions/delivery.ResponseBodyError'
      status:
        type: integer
    type: object
  delivery.ProductListResponse:
    properties:
      body:
        items:
          $ref: '#/definitions/models.ProductInFeed'
        type: array
      status:
        type: integer
    type: object
  delivery.ProductResponse:
    properties:
      body:
        $ref: '#/definitions/models.Product'
      status:
        type: integer
    type: object
  delivery.RedirectBody:
    properties:
      redirect_url:
        type: string
    type: object
  delivery.Response:
    properties:
      body:
        $ref: '#/definitions/delivery.ResponseBody'
      status:
        type: integer
    type: object
  delivery.ResponseBody:
    properties:
      message:
        type: string
    type: object
  delivery.ResponseBodyError:
    properties:
      error:
        type: string
    type: object
  delivery.ResponseRedirect:
    properties:
      body:
        $ref: '#/definitions/delivery.RedirectBody'
      status:
        type: integer
    type: object
  models.Image:
    properties:
      url:
        type: string
    type: object
  models.PreProduct:
    properties:
      available_count:
        type: integer
      category_id:
        type: integer
      city:
        description: nolint
        type: string
      delivery:
        type: boolean
      description:
        description: nolint
        type: string
      images:
        items:
          $ref: '#/definitions/models.Image'
        type: array
      price:
        type: integer
      safe_deal:
        type: boolean
      saler_id:
        type: integer
      title:
        type: string
    type: object
  models.Product:
    properties:
      available_count:
        type: integer
      category_id:
        type: integer
      city:
        description: nolint
        type: string
      created_at:
        type: string
      delivery:
        type: boolean
      description:
        description: nolint
        type: string
      favourites:
        type: integer
      id:
        type: integer
      images:
        items:
          $ref: '#/definitions/models.Image'
        type: array
      in_favourite:
        type: boolean
      price:
        type: integer
      safe_deal:
        type: boolean
      saler_id:
        type: integer
      title:
        type: string
      views:
        type: integer
    type: object
  models.ProductInFeed:
    properties:
      city:
        type: string
      delivery:
        type: boolean
      favourites:
        type: integer
      id:
        type: integer
      images:
        items:
          $ref: '#/definitions/models.Image'
        type: array
      in_favourite:
        type: boolean
      price:
        type: integer
      safe_deal:
        type: boolean
      title:
        type: string
    type: object
  models.UserWithoutID:
    properties:
      birthday:
        description: nolint
        type: string
      email:
        type: string
      name:
        description: nolint
        type: string
      password:
        type: string
      phone:
        description: nolint
        type: string
    type: object
host: 84.23.53.28:8080
info:
  contact: {}
  description: This is a server of YULA server.
  title: YULA project API
  version: "1.0"
paths:
  /logout:
    post:
      consumes:
      - application/json
      description: logout in app
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.Response'
        "222":
          description: Error
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: logout
  /product/add:
    post:
      consumes:
      - application/json
      description: |-
        add product by data
        Error.status can be:
        StatusErrBadRequest      = 400
        StatusErrInternalServer  = 500
      parameters:
      - description: product data for adding
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.PreProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ResponseRedirect'
        "222":
          description: Error
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: add product
  /product/get/{id}:
    get:
      consumes:
      - application/json
      description: get product by id
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ProductResponse'
        "222":
          description: Error
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: get product
  /product/get_list:
    get:
      consumes:
      - application/json
      description: get product by count
      parameters:
      - description: count products
        in: query
        name: count
        required: true
        type: integer
      - description: 'last product id '
        in: query
        name: last_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.ProductListResponse'
        "222":
          description: Error
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: get product
  /signin:
    post:
      consumes:
      - application/json
      description: signin in app
      parameters:
      - description: user data for signin
        in: body
        name: preUser
        required: true
        schema:
          $ref: '#/definitions/models.UserWithoutID'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.Response'
        "222":
          description: Error
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: signin
  /signup:
    post:
      consumes:
      - application/json
      description: |-
        signup in app
        Error.status can be:
        StatusErrBadRequest      = 400
        StatusErrInternalServer  = 500
      parameters:
      - description: user data for signup
        in: body
        name: preUser
        required: true
        schema:
          $ref: '#/definitions/models.UserWithoutID'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.Response'
        "222":
          description: Error
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: signup
schemes:
- http
swagger: "2.0"
