name: build-push-dev

on:
    pull_request:
        branches: [main]
        types:
            - closed
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{github.repository}}
jobs:
    build-main:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Log in to the Github Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: $REGISTRY/$IMAGE_NAME
                  tags: |
                    type=raw,value=main-latest-main
                    
            - name: Build and push
              uses: docker/build-push-action@v5
              id: build
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    build-auth:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Log in to the Github Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: $REGISTRY/$IMAGE_NAME
                  tags: |
                    type=raw,value=auth-latest-main

            - name: Build and push
              uses: docker/build-push-action@v5
              id: build
              with:
                  context: .
                  file: ./services/auth/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    build-fs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Log in to the Github Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: $REGISTRY/$IMAGE_NAME
                  tags: |
                    type=raw,value=fs-latest-main

            - name: Build and push
              uses: docker/build-push-action@v5
              id: build
              with:
                  context: .
                  file: ./services/file_service/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    notify-good:
        runs-on: ubuntu-latest
        if: ${{ always() && needs.build-main.result == 'success' && needs.build-auth.result == 'success' && needs.build-fs.result == 'success' }}
        needs: [build-main, build-auth, build-fs]
        steps:
            - name: send
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_CHAT }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      Билд образа
                        - ${{ github.repository }}:${{github.ref_name}}
                      Закончился с ✅
                      https://github.com/go-park-mail-ru/2023_2_Rabotyagi/commit/${{github.sha}}
    
    notify-bad:
        runs-on: ubuntu-latest
        if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
        needs: [build-main, build-auth, build-fs]
        steps:
            - name: Send Bad Notification
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_CHAT }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      Билд образа
                        - ${{ github.repository }}:${{github.ref_name}}
                      Закончился с ❌
                      https://github.com/go-park-mail-ru/2023_2_Rabotyagi/actions/runs/${{github.run_id}}
