// Code generated by MockGen. DO NOT EDIT.
// Source: internal/product/delivery/comment_handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/product/delivery/comment_handler.go -destination=internal/product/mocks/comment_handler.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2023_2_Rabotyagi/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockICommentService is a mock of ICommentService interface.
type MockICommentService struct {
	ctrl     *gomock.Controller
	recorder *MockICommentServiceMockRecorder
}

// MockICommentServiceMockRecorder is the mock recorder for MockICommentService.
type MockICommentServiceMockRecorder struct {
	mock *MockICommentService
}

// NewMockICommentService creates a new mock instance.
func NewMockICommentService(ctrl *gomock.Controller) *MockICommentService {
	mock := &MockICommentService{ctrl: ctrl}
	mock.recorder = &MockICommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICommentService) EXPECT() *MockICommentServiceMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockICommentService) AddComment(ctx context.Context, r io.Reader, userID uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", ctx, r, userID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddComment indicates an expected call of AddComment.
func (mr *MockICommentServiceMockRecorder) AddComment(ctx, r, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockICommentService)(nil).AddComment), ctx, r, userID)
}

// DeleteComment mocks base method.
func (m *MockICommentService) DeleteComment(ctx context.Context, commentID, senderID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, commentID, senderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockICommentServiceMockRecorder) DeleteComment(ctx, commentID, senderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockICommentService)(nil).DeleteComment), ctx, commentID, senderID)
}

// GetCommentList mocks base method.
func (m *MockICommentService) GetCommentList(ctx context.Context, offset, count, userID uint64) ([]*models.CommentInFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentList", ctx, offset, count, userID)
	ret0, _ := ret[0].([]*models.CommentInFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentList indicates an expected call of GetCommentList.
func (mr *MockICommentServiceMockRecorder) GetCommentList(ctx, offset, count, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentList", reflect.TypeOf((*MockICommentService)(nil).GetCommentList), ctx, offset, count, userID)
}

// UpdateComment mocks base method.
func (m *MockICommentService) UpdateComment(ctx context.Context, r io.Reader, userID, commentID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ctx, r, userID, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockICommentServiceMockRecorder) UpdateComment(ctx, r, userID, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockICommentService)(nil).UpdateComment), ctx, r, userID, commentID)
}
