// Code generated by MockGen. DO NOT EDIT.
// Source: internal/product/usecases/favourite_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/product/usecases/favourite_service.go -destination=internal/product/mocks/favourite_service.go --package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2023_2_Rabotyagi/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIFavouriteStorage is a mock of IFavouriteStorage interface.
type MockIFavouriteStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIFavouriteStorageMockRecorder
}

// MockIFavouriteStorageMockRecorder is the mock recorder for MockIFavouriteStorage.
type MockIFavouriteStorageMockRecorder struct {
	mock *MockIFavouriteStorage
}

// NewMockIFavouriteStorage creates a new mock instance.
func NewMockIFavouriteStorage(ctrl *gomock.Controller) *MockIFavouriteStorage {
	mock := &MockIFavouriteStorage{ctrl: ctrl}
	mock.recorder = &MockIFavouriteStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFavouriteStorage) EXPECT() *MockIFavouriteStorageMockRecorder {
	return m.recorder
}

// AddToFavourites mocks base method.
func (m *MockIFavouriteStorage) AddToFavourites(ctx context.Context, userID, productID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToFavourites", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToFavourites indicates an expected call of AddToFavourites.
func (mr *MockIFavouriteStorageMockRecorder) AddToFavourites(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToFavourites", reflect.TypeOf((*MockIFavouriteStorage)(nil).AddToFavourites), ctx, userID, productID)
}

// DeleteFromFavourites mocks base method.
func (m *MockIFavouriteStorage) DeleteFromFavourites(ctx context.Context, userID, productID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFromFavourites", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFromFavourites indicates an expected call of DeleteFromFavourites.
func (mr *MockIFavouriteStorageMockRecorder) DeleteFromFavourites(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFromFavourites", reflect.TypeOf((*MockIFavouriteStorage)(nil).DeleteFromFavourites), ctx, userID, productID)
}

// GetUserFavourites mocks base method.
func (m *MockIFavouriteStorage) GetUserFavourites(ctx context.Context, userID uint64) ([]*models.ProductInFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFavourites", ctx, userID)
	ret0, _ := ret[0].([]*models.ProductInFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFavourites indicates an expected call of GetUserFavourites.
func (mr *MockIFavouriteStorageMockRecorder) GetUserFavourites(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFavourites", reflect.TypeOf((*MockIFavouriteStorage)(nil).GetUserFavourites), ctx, userID)
}
